version: "2"

linters:
  default: standard
  enable:
    - bodyclose
    - contextcheck
    - errorlint
    - gosec
    - nilerr
    - nilnil
    - revive
    - unconvert
    - usestdlibvars
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    govet:
      enable-all: true
    misspell:
      locale: UK
    revive:
      confidence: 0.8
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin\.go$
      - examples$
      - spec_tests$

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin\.go$
      - examples$
      - spec_tests$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true
