services:
  test:
    build:
      context: .
      target: spec-tests
      args:
        TARGETARCH: ${TARGETARCH:-amd64}
    environment:
      # avoid running component test on dev machine
      GATEWRIGHT_COMP_TESTS: "docker"
    command: pytest -q -p no:cacheprovider /comp_tests
